<a href="https://colab.research.google.com/github/anushree1125/DS_ML-widpython/blob/main/Task_4_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Task-4 : Questions on Numpy***

***Reg no: 3122***

*1.Import the numpy package under the name np and Print the numpy version and the configuration* 

In [ ]:
import numpy as np
print(np.__version__)
print(np.__config__)

1.19.5
<module 'numpy.__config__' from '/usr/local/lib/python3.7/dist-packages/numpy/__config__.py'>


***2.Create a null vector of size 10***

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


***3.Create Simple 1-D array and check type and check data types in array***

In [ ]:
a=np.array([1,2,3])
print(a)
print(type(a))
print(a.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


***4.How to find number of dimensions, bytes per element and bytes of memory used?***

In [ ]:
a=np.array([[1,2,3],[10,11,12]])
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size)

2
8
int64
6


***5.Create a null vector of size 10 but the fifth value which is 1***

In [ ]:
a=np.zeros(10)
print(a)
print("Updated value")
a[5]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated value
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


***6.Create a vector with values ranging from 10 to 49***

In [ ]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

***7.Reverse a vector (first element becomes last)***

In [ ]:
a=np.array([1,2,3])
print(a)
b=np.flipud(a)
print(b)

[1 2 3]
[3 2 1]


***8.Create a 3x3 matrix with values ranging from 0 to 8***

In [ ]:
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


***9.Find indices of non-zero elements from [1,2,0,0,4,0]***

In [ ]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

***10.Create a 3x3 identity matrix***

In [ ]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***11.Create a 3x3x3 array with random values***

In [ ]:
a=np.random.random((3,3,3))
print(a)

[[[3.77546177e-01 8.99938744e-02 2.06156641e-01]
  [3.95690448e-01 4.81642077e-01 6.52906439e-01]
  [3.91748945e-04 9.26248375e-02 6.75776632e-01]]

 [[8.23261179e-01 1.75517492e-01 8.26781952e-01]
  [4.78589499e-01 8.15832586e-01 4.71788095e-01]
  [9.98790488e-01 2.74589565e-01 1.83450526e-01]]

 [[6.28139555e-01 2.90464026e-02 4.30678032e-02]
  [2.00505845e-01 4.56728529e-01 9.65176477e-01]
  [2.09097452e-01 2.97655441e-03 6.01941332e-01]]]


***12.Create a 10x10 array with random values and find the minimum and maximum values***

In [ ]:
a=np.random.random((10,10))
print(a)
print("Min=")
print(a.min())
print("Max=")
print(a.max())

[[0.42859252 0.47784054 0.00177548 0.22786846 0.70959949 0.49108602
  0.95815624 0.97534822 0.56014718 0.80227545]
 [0.5791987  0.75725387 0.54898968 0.29061195 0.90493092 0.5623387
  0.90077207 0.92096451 0.32454881 0.9172058 ]
 [0.71244434 0.87742663 0.70042166 0.94380005 0.97756745 0.30547136
  0.06512592 0.90385043 0.56830503 0.18305649]
 [0.57961004 0.52230704 0.55745703 0.91764106 0.06341718 0.16342465
  0.02932961 0.07830943 0.62723455 0.88441399]
 [0.82932682 0.61022595 0.55700419 0.41695299 0.84940727 0.36632373
  0.69325067 0.83430236 0.0206513  0.31092323]
 [0.16658629 0.29314411 0.40337439 0.61946714 0.2077502  0.93695235
  0.54500628 0.60251715 0.18119878 0.2479444 ]
 [0.38334517 0.80335569 0.72622987 0.75303119 0.83103965 0.55706433
  0.42946908 0.07473432 0.28944421 0.89369094]
 [0.57963941 0.65667762 0.85409656 0.33544408 0.18786008 0.34377016
  0.68325193 0.12412811 0.47385121 0.45567348]
 [0.04644601 0.3830924  0.28980125 0.1379276  0.21770681 0.9332763
  0.07079407 0

***13.Create a random vector of size 30 and find the mean value***

In [ ]:
a=np.random.random(30)
print(a)
b=np.mean(a)
print("mean=")
print(b)

[9.14067086e-01 9.57287913e-01 5.28424490e-01 1.00123240e-04
 2.99641982e-01 4.49039071e-01 2.50324662e-01 7.44790322e-01
 1.84344654e-01 5.31595911e-01 5.51614787e-01 1.38345871e-02
 3.72439690e-01 2.15814628e-01 7.72712925e-01 1.24681735e-01
 5.77737280e-01 3.69606584e-01 4.08484594e-01 7.57627400e-01
 7.05556403e-01 4.11797246e-01 8.30012469e-01 5.01225733e-01
 6.12906711e-01 6.20168084e-01 4.97590916e-01 7.46308184e-02
 8.35054373e-01 2.92457297e-01]
mean=
0.48018568246067495


***14.Create a 2d array with 1 on the border and 0 inside***

In [ ]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


***15.How to add a border (filled with 0's) around an existing array? ***

In [ ]:
a=np.ones((5,5))
print(a)
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


***16.How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?***

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20  

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print("1st row only")
print(a[0:1,0:7])
print(" get 13th element")
print(a[1:2,5:6])
print("3rd column")
print(a[:,2:3])
print("get [2, 4, 6]")
print(a[0:1,1::2])
print("replace 13 by 20")
a[1][5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
1st row only
[[1 2 3 4 5 6 7]]
 get 13th element
[[13]]
3rd column
[[ 3]
 [10]]
get [2, 4, 6]
[[2 4 6]]
replace 13 by 20
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


***17.How to Convert a 1D array to a 2D array with 2 rows***

In [ ]:
a=np.array([1,2,3,4,5,6])
print(a)
b=a.reshape(2,3)
print("2D array")
print(b)

[1 2 3 4 5 6]
2D array
[[1 2 3]
 [4 5 6]]


***18.Create the following pattern without hardcoding. Use only numpy functions and the below input array a.***

In [ ]:
a=np.array([1,2,3])
a=np.append(np.repeat(a,3),np.tile(a,3))
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

***19.Write a program to show how Numpy taking less memory compared to Python List?***

In [ ]:
l=range(1000)
import sys
print(sys.getsizeof(a))
a=10
print("memory used by list:")
print(sys.getsizeof(a)*len(l))
a1=np.arange(1000)
print(a1.size)
print("memory used by numpy:")
print(a1.size*a1.itemsize)

28
memory used by list:
28000
1000
memory used by numpy:
8000


***20.Write a program to show how Numpy taking less time compared to Python List?***

In [ ]:
import time
import sys
size=1000000
l1=range(size)
l2=range(size)
n1=np.arange(size)
n2=np.arange(size)
start=time.time()
result=[(x+y)for x,y in zip(l1,l2)]
print("Time taken by python list")
print((time.time()-start)*1000)
start=time.time()
result=n1+n2
print("Time taken by numpy")
print((time.time()-start)*1000)


Time taken by python list
135.22958755493164
Time taken by numpy
14.394044876098633
